apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: quiz
  labels:
    app: frontend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: thinhduckhoi/frontend-js:7acd2b33a2375b43a986f7147131abef9555ddc9
        env:
        - name: VITE_REACT_APP_API_URL
          value: "http://devsecops.khoidevops.space/api/questions"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: quiz
spec:
  selector:
    app: frontend
  ports:
  - port: 8080
    protocol: TCP
  type: ClusterIP
